CREATE TABLE Users
(
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Users_Id PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    Password NVARCHAR(256) NULL,
    PasswordHash VARBINARY(MAX) NULL,
    PhoneNumber NVARCHAR(50) NULL,
    LastLogin DATETIME2(7) NULL,
    CreatedDate DATETIME2(7) NOT NULL CONSTRAINT DF_Users_CreatedDate DEFAULT (SYSUTCDATETIME()),
    ModifiedDate DATETIME2(7) NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT (1),
    IsDeleted BIT NOT NULL CONSTRAINT DF_Users_IsDeleted DEFAULT (0),
    CONSTRAINT UQ_Users_Email UNIQUE (Email)
);